# Generated by Django 5.2 on 2026-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
