# Generated by Django 5.2 on 2026-06-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0017_booking_booking_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='bookings.service')),
            ],
            options={
                'verbose_name_plural': 'manual service entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
