# Generated by Django 5.2 on 2026-03-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopSettings',
            new_name='ShopSetting',
        ),
        migrations.RenameField(
            model_name='shopsetting',
            old_name='otp_enabled',
            new_name='is_otp_enabled',
        ),
    ]
