# Generated by Django 5.2 on 2026-01-18 09:24

import django.db.models.deletion
from django.db import migrations, models



def clear_bookings(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_customertrust_booking_ip_address_booking_is_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_bookings),
        migrations.RemoveField(
            model_name='booking',
            name='services',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.service'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'time'), name='unique_service_slot'),
        ),
    ]
