# Generated by Django 5.2 on 2026-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_services_booking_booking_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
