# Generated by Django 5.2 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_end_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_service_slot',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'completed', 'pending_otp'])), fields=('service', 'date', 'time'), name='unique_active_service_slot'),
        ),
    ]
