# Generated by Django 5.2 on 2026-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_unique_service_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
